### ISSUE TITLE
Implement icons and images

### ISSUE THREAD

**Issue by hoodie** [hoodie/notify-rust#13]
Greatings brave contributor 🧙
Behold! This issue has remained unresolved for many a month. Are you cunning enough to resolve it? Study the [ancient scrolls](https://developer.gnome.org/notification-spec/#icons-and-images)! Challenge the congenialness of the great implementations Gnome, KDE and Unity. Proclaim your victory by filing a pull request.

Good luck traveler!

**Comment by hoodie** [comment]
This could potentially be feature guarded because it might add additional dependencies

**Comment by hannesg** [comment]
Hi

I heard your call and worked a bit on this over the last days. I have a rough working version but I'm currently stuck with a design problem and would appreciate some feedback. Here is the patch: https://github.com/hannesg/notify-rust/commit/415a8ff78af0727250efec1f75c0a89a79376abd

It looks like the hint key for image data changed in spec version 1.0, 1.1, 1.2. So in order to convert a NotificationHint into a dbus::MessageItem we have to know which spec version is implemented. I've solved this by adding a call to get_server_information() in _show() ( https://github.com/hannesg/notify-rust/commit/415a8ff78af0727250efec1f75c0a89a79376abd#diff-b4aea3e418ccdb71239b96952d9cddb6R379 ) but I'm not happy with that. libnotify does this call only once when initialized. Should we do the same?
Moreover, I'm not satisfied with having the implementation of 'From<NotificationHint> for MessageItem' assuming a certain spec version ( https://github.com/hannesg/notify-rust/commit/415a8ff78af0727250efec1f75c0a89a79376abd#diff-7014bd08b5309cb96a4a77632db54c6aR271 ). Should we drop this implementation?

**Comment by hoodie** [comment]
awesome - I'll try to review this until friday - what platforms have you tested this on? my usual candidates were GNOME3, Plasma and xfce.

**Comment by hannesg** [comment]
I've tested it on ubuntu 16.04 with notify-osd 0.9.35 which implements spec version 1.1.

**Comment by hoodie** [comment]
sorry that I didn't respond until now. I'm surprised that this even works on KDE - I'm gonna give it a spin on gnome (right after it's finished installing). The spec version check seems to be ok, we could make that static using [lazy static](https://crates.io/crates/lazy_static). Another option would be to just send all three versions all the time :D
Other than that this looks pretty good. Thank you very much ❤️

**Comment by hoodie** [comment]
@hannesg wanna make this a PR?

**Comment by hoodie** [comment]
@hannesg if you don't mind I would like to adapt your solution
