### ISSUE TITLE
Support for other OSes

### ISSUE THREAD

**Issue by jonhoo** [hoodie/notify-rust#22]
I noticed the comment over at https://github.com/hoodie/notify-rust/issues/10#issuecomment-145005151, which seemed to indicate that there is some interest in supporting notification support for other platforms through the same library. I think that would be *really* nice too, and having a tracking issue for it is a good start.

**Comment by hoodie** [comment]
It is 😆 
Even though this libs API is rather linux specific it might be possible to whip something up. Do you happen to have windows experience?

**Comment by jonhoo** [comment]
Sorry, no, and not with macOS either. A cursory review suggests that notifications do [have an API](https://msdn.microsoft.com/en-us/library/windows/desktop/ee330740(v=vs.85).aspx), but I have no experience with it whatsoever.

The reason I bring it up is that I'd like my mail notification tool [buzz](https://github.com/jonhoo/buzz) to work on other platforms, but given that I only use Linux personally, it's a pretty second-order concern :p

**Comment by Susurrus** [comment]
I have no experience with notifications on Windows or Mac, but I do have both platforms so I could test on them. A cross-platform notifications crate would be awesome.

**Comment by hoodie** [comment]
alright @jonhoo and @Susurrus, I'm throwing the ⚽️ back your direction, I just added macOS support thanks to the exceptional work of @h4llow3En 🎃. Please test this if you can, I'm not putting out a release just yet, since on macOS we only support a subset of the functionality. **Plus** I make no promises on windows support any time soon 😉

**Comment by Susurrus** [comment]
Is the Mac stuff documented anywhere? Looks like it was merged but the readme still only talks about dbus, which I don't think is used for OS X. Since there are limitations, I don't want to report things already known. Can someone add Mac documentation somewhere? I'll test this out tomorrow.

**Comment by Boscop** [comment]
It would be awesome to have windows support, too.
https://msdn.microsoft.com/en-us/library/windows/desktop/ee330740(v=vs.85).aspx

**Comment by Susurrus** [comment]
Probably the first step for Windows support would be to make sure the necessary functions and constants are defined in the [winapi-rs](https://github.com/retep998/winapi-rs) crate. Once that's done it'll be a lot easier to integrate the necessary functionality here.

**Comment by Susurrus** [comment]
I also wanted to ask will this build on Windows right now? I'd like to try supporting this in my application, but I don't want to commit something that fails on one of my supported platforms. It would be great if a dummy implementation that does nothing could be implemented for Windows so that I wouldn't need to conditionally compile in this library and do the same in my code.

**Comment by hoodie** [comment]
as this started out as a pure linux/bsd I haven't put any measures in place to guarantee that. You can add `target` flags like [these](https://github.com/hoodie/notify-rust/blob/master/Cargo.toml#L24) though

**Comment by hoodie** [comment]
closing for now- mac is sorta supported and windows is too far off
