### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by Susurrus** [hoodie/notify-rust#25]
Redirecting from #22 to keep this a little more focused, the Mac support has the following issues:

1. The following examples don't compile:
  * actions
  * countdown
  * info
  * on_close
  * server
  * update
  * wait_for_closing
2. Text formatting isn't correct. See the following screenshot for notifications. Note also that clicking the notification takes me to the terminal. I'm not certain if that is the "correct" behavior here.
![screen shot 2017-03-13 at 11 37 07 am](https://cloud.githubusercontent.com/assets/206363/23869778/6c30085c-07e1-11e7-8418-18a815ec852e.png)
3. The following examples didn't work correctly:
  * hints (no notifications shown)
  * show_volume (nothing happens)
  * urgency (all notifications are identical and urgency from string doesn't have a title)

Pinging @h4llow3En as they appear to have done most of this work.

Again, there's no mac-specific documentation that I've found, so I'm unsure what I should expect to work or if these are all known issues. So I just posted everything. I'm happy to test code changes and also read over any documentation changes, just let me know. Really excited that cross-platform support is materializing!

**Comment by hoodie** [comment]
Thanks for the screenshot, we get the same results. You could change the icon by pretending to be another app using [set_application](https://github.com/h4llow3En/mac-notification-sys/blob/master/src/lib.rs#L140) which I [reexport](https://github.com/hoodie/notify-rust/blob/d9838e8816219a8720b712684caca57b92add9f5/src/lib.rs#L94)/
The html-table example actually works nowhere, it's just an experiment, perhaps someday gnome or kde will cover it. If you look at the documentation (`rust doc --open`) you'll find mention that, due to the slim possibilities of the [NSNotification](https://developer.apple.com/reference/foundation/nsnotification) API you get nothing but the most bare bone notification. It's not as nice as the [galago](http://www.galago-project.org/specs/notification/0.9/index.html) which the xdg desktops implement (sorta).
For anything more you're either gonna have to reimplement some of the macOS functionality to mimic that of the better unixes 😉 , or make the settings in your `/Applications/someapp`.


![its something](http://i2.kym-cdn.com/photos/images/newsfeed/000/114/139/tumblr_lgedv2Vtt21qf4x93o1_40020110725-22047-38imqt.jpg)

**Comment by Susurrus** [comment]
It'd be nice then if you could embed this into the type something somehow. Maybe a `RichNotification` and `Notification`/`BareNotification` type where there are specific guarantees as to what `RichNotification` supports. So on Linux it'd support both types and Mac would only support `Notification`/`BareNotification`. It's nice embedding as much as possible into the type system with Rust.

**Comment by Susurrus** [comment]
And `BareNotification` can check for HTML tags and trigger a panic on initialization if that's the case in order to enforcce this.

**Comment by hoodie** [comment]
My idea was to allow you to reuse as much of your code as possible on macOS, so do don't need to know where your app will run, of course this does not work for things like `actions`, I admit. Perhaps we could split the notification up into a container and a set of traits. About the HTML detection, that might be a job for another crate.

**Comment by h4llow3En** [comment]
If you have any good solution to catch actions, I would be really happy to listen to. Because the NSUserNotificationCenterDelegate has to catch any actions from the Notification and has to stay active. This is tricky because (in mac-notification-sys) I just tell the name of the application I want the notification to be from. I am still trying to figure it out properly. Please be my guest if you have some ideas :-)
AFAIK I am not able to set the notification alert style either.

**Comment by Susurrus** [comment]
Maybe it's also worth minimizing features to a smaller subset that is more supported across platforms. For example it looks like there is minimal support for `hint` and `urgency`, why not just remove those?

**Comment by h4llow3En** [comment]
This is true but as I know @hoodie wanted to implement als function of the standard. Even nearly no one use it completely.

**Comment by hoodie** [comment]
I though about several ways to treat methods of `NotificationHandle` which are not available on macOS. In the end the consumer of this crate will have to handle the different platforms in one way of the other, no matter what solution we choose. Therefore I think the current solution (different `NotificationHandle` types on mac an xdg) is just as helpful as any other. As long as you don't use actions or wait for closing you wont notice the difference, when you do you're going to have to add a `#[cfg(...)]`.

**Comment by kiliankoe** [comment]
Would it maybe be possible to add some platform-agnostic helpers so a consumer would not have to care about platform-specific differences if they're not interested in advanced functionality?

**Comment by hoodie** [comment]
@kiliankoe that is already the case I guess, you currently get a `NotificationHandle` on xdg and mac. If you don't use e.g. `.wait_for_closing()` you won't notice the difference. Since that method is not implemented on mac, you'll get a compiletime error. In that case you would have to wrap your code the way I did in the [example](https://github.com/hoodie/notify-rust/blob/master/examples/wait_for_closing.rs).

**Comment by Susurrus** [comment]
So is all that's left for this to add MacOS details to the docs and all relevant functions? It doesn't sound like abstracting this out a bit so that errors are handled at the type-level is a goal for now.

**Comment by hoodie** [comment]
There are already notes about platform support in the documentation where differences exist. As for type level changes, I don't see that big a difference for the consumer. You'll have to catch the differences on the consumer-side either way. The current approach should even allow for this to be a minor version change. If you find the current code documentation insufficient I'd appreciate input.

**Comment by frewsxcv** [comment]
It might be possible to just depend on https://github.com/h4llow3En/mac-notification-sys, no?

**Comment by frewsxcv** [comment]
FWIW, I just tried running this code and no notification shows for me on macOS 10.12.3 with notify-rust 3.3.0:

```rust
extern crate notify_rust;

fn main() {
    notify_rust::Notification::new()
        .summary("Firefox News")
        .body("This will almost look like a real firefox notification.")
        .icon("firefox")
        .show().unwrap();
}
```

The previous library I linked seems to work fine though.

**Comment by h4llow3En** [comment]
You have to set a application I stead of an icon.

On macOS a notification only can be delivered if you are a valid application in you applications folder and a valid plist.
In your case this should trigger a notification with the default application (and icon) `Terminal`

**Comment by frewsxcv** [comment]
How about something like this?

```rust
    use notify_rust::Notification;
    use notify_rust::NotificationHint as Hint;
    Notification::new()
        .summary("Category:email")
        .body("This has nothing to do with emails.\nIt should not go away until you acknoledge it.")
        .appname("Terminal")
        .timeout(1000)
        .show().unwrap();
```

For this one, a notification appears in the macOS Notifications Center, but nothing appears on screen.

**Comment by h4llow3En** [comment]
Could it be possible you have turned on "Do Not Disturb"?
It is not possible to only show a notification in the Notification Center. The notification `always` will be delivered from the OS itself.

**Comment by frewsxcv** [comment]
"Do Not Disturb" mode is off. What is the format for `appname`? No matter what I put in there, it seems to come up with a Terminal.app icon.

**Comment by h4llow3En** [comment]
As you can see [here](https://github.com/hoodie/notify-rust/blob/master/src/lib.rs#L366) the application or icon is not used, because in my crate you have to set it manualy.
An application can only be set one while running.
As I found out now, this is one thing we forgot to implement in notify-rust, sorry.

**Comment by hoodie** [comment]
@h4llow3En wanna do that or should I ?

**Comment by hoodie** [comment]
Actually this is more a documentation issue.  This is due to the different semantics on Mac. Since you can only do that once per runtime of an app it is better to do it manually, the `.appname()` suggests that it is possible to change for every notification. That is possible on Linux though, not on Mac.

**Comment by frewsxcv** [comment]
Figured out my earlier issue: https://github.com/frewsxcv/alert-after/pull/12#issuecomment-291378658

If you specify the `"terminal"` bundle, and Terminal.app is currently active, it won't display the notification.

**Comment by jaroslaw-weber** [comment]
worked once then stopped working. i used "firefox" and had it opened all the time.

**Comment by hoodie** [comment]
@jaroslaw-weber I don't undestand? What is your problem? Are you talking about notify-rust or alert-after?
