### ISSUE TITLE
macos: Notifications go into the tray but don't pop up on screen.

### ISSUE THREAD

**Issue by asmyers** [hoodie/notify-rust#39]
When I run a simple notification on MacOS I get a notification in the tray but I don't get the quick popup that I'm used to seeing for other notifications.  Is there a way to enable this?

**Comment by hoodie** [comment]
I'm not sure what you mean. This lib should not affect the tray at all, perhaps @h4llow3En can shed some light on this.

**Comment by asmyers** [comment]
On OSX there's a hamburger icon which you click to open a list of notifications:

<img width="371" alt="screen shot 2017-10-27 at 10 57 40 am" src="https://user-images.githubusercontent.com/122908/32110552-c81a0686-bb05-11e7-925c-3e0bf0c2b2ef.png">

When I run an example with main() containing this:

```
    Notification::new().timeout(10)
        .summary("Firefox News")
        .icon("firefox")
        .appname("work-break")
        .show().unwrap();
```

The notification goes straight into the notification list without ever appearing on the desktop.

I'm on MacOS 10.12.6

**Comment by h4llow3En** [comment]
Please have a look in the docs for macOS (you have to generate them by yourself)
Then you will notice that .icon and .appname have no effect. Since notify-rust does not support the option to set a bundleid (the application identifier of an *installed* application) it will send always with the terminal application. And notifications are never pop up on screen if the application is active

**Comment by hoodie** [comment]
This could probably be better documented. On mac you can use `set_application()` to impersonate another application. This should change the icon, but you can only do that once - which is why we didn't link it with the existing `.appname()` method. The notification semantics on the differen OSs are different enough that this api requires the users to catch some of the corner cases themselves unfortunately.
